version: "3"
services:
    neo4j:
        image: discsports/neo4j-apoc
        environment:
          - NEO4J_AUTH=none
          - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        volumes:
          - "~/Downloads/import:/import"
        ports:
          - '7474:7474'
          - '7473:7473'
          - '7687:7687'

    web:
        build: .
        command: node src/app.js
        volumes:
          - "~/Downloads/import:/import"
        ports:
          - "3000:3000"
        depends_on:
          - neo4j
