version: '3.3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - '8000:5000'
    depends_on:
      - neo4j

